// Generated by   : ImageConverter 565 Online
// Generated from : wlanerror.png
// Time generated : Mon, 17 Jun 19 01:38:09 +0200  (Server timezone: CET)
// Image Size     : 7x5 pixels
// Memory usage   : 70 bytes


#if defined(__AVR__)
    #include <avr/pgmspace.h>
#elif defined(__PIC32MX__)
    #define PROGMEM
#elif defined(__arm__)
    #define PROGMEM
#endif

const unsigned short wlanerror[35] PROGMEM={
0xFEC0, 0xF800, 0xF800, 0xF800, 0xF800, 0xF800, 0xFEC0, 0xF800, 0xFEC0, 0xFEC0, 0x0000, 0xFEC0, 0xFEC0, 0xF800, 0x0000, 0x0000,   // 0x0010 (16) pixels
0xF800, 0xFEC0, 0xF800, 0x0000, 0x0000, 0x0000, 0xFEC0, 0xFEC0, 0x0000, 0xFEC0, 0xFEC0, 0x0000, 0xFEC0, 0x0000, 0x0000, 0xF800,   // 0x0020 (32) pixels
};
